Correct some typos and make small improvements on GettingStarted.mo
OpenIPSL/OpenIPSL pull request #278
Opened 2021-08-22 17:14 UTC by max-privato

Fix some typos and make other improvements on gettingStarted.mo

2021-08-23 09:06 UTC, dietmarw commented on OpenIPSL/UsersGuide/GettingStarted.mo
> +The <strong><code>OpenIPSL</code></strong> was developed to be a familiar alternative to traditional
Unnecessary trailing white space introduced.

2021-08-23 09:09 UTC, dietmarw requested changes

2021-08-23 09:09 UTC, dietmarw commented on OpenIPSL/UsersGuide/GettingStarted.mo
> +All models in a Modelica library require initial guess values that should come from a solution of
whitespace

2021-08-23 09:09 UTC, dietmarw commented on OpenIPSL/UsersGuide/GettingStarted.mo
> +However, there is no power flow solver associated to the library as of the present time.
whitespace

2021-08-23 09:09 UTC, dietmarw commented on OpenIPSL/UsersGuide/GettingStarted.mo
> +All models in <strong><code>OpenIPSL</code></strong> are programmed in such way that by introducing a <a href=\"https://github.com/SmarTS-Lab/Raw2Record\">power flow solution</a> (from another tool),
Replacing `&amp;` will cause issues.

2021-08-23 09:09 UTC, dietmarw commented on OpenIPSL/UsersGuide/GettingStarted.mo
> +The <b>pfComponent</b> also provides support for the common <b>SystemBase</b> component that in turn provides a single instance of the system's common parameters, i.e., frequency and base power.
don't use `b`, `strong` is the correct one.

2021-08-23 14:36 UTC, max-privato commented
I'm rather new to pull requests discussions.
I agree to correct spaces and substitute /b with /strong.
I don't see where &amp was used, but I understand that this is a technical change, and therefore I agree with your suggestion regarding it.

Unfortunately, I don't know if I have to do anything to accept these changes, and how to do this...
I would be glad if you do these small changes yourself.

2021-08-31 13:43 UTC, dietmarw commented
Since the fixes are so minor and isolating the typo fixes from the wrong syntax changes takes far more time to solve I'm going to close this PR unmerged. The getting started guide will most likely get updated again anyway. I hope you understand. Feel free to attempt another PR with clean changes that don't contain unwanted changes that would also break CI.

2021-08-31 13:44 UTC, closed without merging

2021-08-31 16:31 UTC, max-privato commented
> Since the fixes are so minor and isolating the typo fixes from the wrong syntax changes takes far more time to solve I'm going to close this PR unmerged. The getting started guide will most likely get updated again anyway. I hope you understand. Feel free to attempt another PR with clean changes that don't contain unwanted changes that would also break CI.

Sure I understand.
Frankly I don't understand what caused the wrong syntax, so that to propose clean changes.
I don't remember exactly  but I used dymola or openmodeloca to implement the proposed changes.