Fixing softPMU and increasing tests' and examples' compatibility with OMEdit
OpenIPSL/OpenIPSL pull request #291
Opened 2022-05-27 02:42 UTC by marcelofcastro

This PR is supposed to fix:
- SoftPMU implementation and the frequency calculation block.
- Initial condition information which prevented models from simulating in OpenModelica
- Warning related to Fault Event (by replacing 0 to C.eps in some examples and tests)

Therefore, issues:
#173 and #245 are addressed in this PR.

2022-05-27 18:11 UTC, dietmarw commented
Any chance to isolate the softPMU part into a separate PR. I still see quite a bit of an issue there and don't want it to be in the way of the OM fixes.

2022-05-27 19:41 UTC, marcelofcastro commented
I think we can discuss here the issues you see with the SoftPMU thing

2022-05-30 13:55 UTC, dietmarw requested changes
Please remove all the `"V.A"` and `"V"` displayUnit modifiers. Those are already set correctly in the types and this override does not make sens and makes the numbers even harder to read.

2022-05-30 13:55 UTC, dietmarw commented on OpenIPSL/Examples/SevenBus/Network.mo
> +    M_b(displayUnit = "V.A") =1710000000,
This should better be `"MVA"`

2022-05-30 13:55 UTC, dietmarw commented on OpenIPSL/Examples/SevenBus/Network.mo
> +    M_b(displayUnit = "V.A") =1211000000,
MVA

2022-05-30 13:55 UTC, dietmarw commented on OpenIPSL/Examples/SevenBus/Network.mo
> +  Electrical.Buses.Bus internal_bus_gen2(S_b(displayUnit = "V.A") = 1710000000,V_b = 20000,angle_0=PF_results.voltages.A61, v_0=
MVA

2022-05-30 13:55 UTC, dietmarw commented on OpenIPSL/Tests/BaseClasses/LoadTestBase.mo
> +    Sn(displayUnit = "V.A")= 20000000,
MVA

2022-05-30 13:55 UTC, dietmarw commented on OpenIPSL/Tests/BaseClasses/TGTestBase.mo
> +    Sn(displayUnit = "V.A") =20000000,
MVA

2022-05-31 14:48 UTC, dietmarw approved these changes
Looks good now.

2022-05-31 14:50 UTC, merged