Invalid == on Reals NegCurLogic
OpenIPSL/OpenIPSL pull request #326
Opened 2022-11-11 23:26 UTC by gkhalley

Meant to apply to #315 . OpenIPSL.Tests.Controls.PSSE.ES.SCRX builds and runs in WSM 13.2. Previously it didn't.

2022-11-14 09:59 UTC, dietmarw requested changes
Thanks. If you remove the decimal points this should be good to go.

2022-11-14 09:59 UTC, dietmarw commented on OpenIPSL/NonElectrical/Logical/NegCurLogic.mo
> +  Crowbar_V = if not (RC_rfd > 0.0 or RC_rfd < 0.0) then 0 else (-1)*RC_rfd*XadIfd;
```suggestion
  Crowbar_V = if not (RC_rfd > 0 or RC_rfd < 0) then 0 else (-1)*RC_rfd*XadIfd;
```

2022-11-15 00:11 UTC, gkhalley reviewed
I understand and appreciate your guidance. I will make sure to do that next time. I think I have done everything necessary, but let me know if I didn't.

2022-11-15 12:18 UTC, dietmarw approved these changes

2022-11-15 12:22 UTC, merged