New PSSE models
OpenIPSL/OpenIPSL pull request #347
Opened 2024-08-15 18:37 UTC by GiuseppeLaera

New control models from PSSE library have been implemented

2024-08-15 18:44 UTC, lvanfretti commented
@marcelofcastro I talked to @GiuseppeLaera to get the models form the Dominion project into the library.
They need some cleaning up, can you please review?
If you require changes, please assign to both @GiuseppeLaera and @lvanfretti so that one of us takes care of this.
I need this to be merged so I can also add the manual implementation and automated implementation of several plants that we made and should be put under the "Examples" sub-package.

2024-09-16 06:39 UTC, dietmarw commented
This PR is introducing 4 (!) new PI(D) controllers. Please argue very carefully why this is needed and why `Modelica.Blocks.Continuous.LimPID` can not be used instead.

2024-10-30 04:23 UTC, lvanfretti commented
@GiuseppeLaera can you please give us an update on the progress? We were targeting to prepare a release on Oct. 31st... but we can't move forward with #341 without the changes needed here.

2024-10-30 10:29 UTC, GiuseppeLaera commented
@lvanfretti I am trying to be done with the updates of the models by the end of next week (10th of November)

2024-11-04 20:38 UTC, lvanfretti commented
@GiuseppeLaera thanks for letting us know, how are the updates coming along?

2024-11-07 20:04 UTC, GiuseppeLaera commented
I have just made a new commit

2024-11-08 16:54 UTC, lvanfretti commented
> I have just made a new commit

Thanks @GiuseppeLaera, really appreciate it!
@fachif please keep an eye on the progress of this PR so you can finish up with yours.

2024-11-08 18:14 UTC, dietmarw requested changes
I've done a couple of clean up commits so that the new contribution follows our code conventions. Please looks also at the inline comments, especially regarding the changes to HYGOV

2024-11-08 18:43 UTC, dietmarw commented
@GiuseppeLaera I've implemented the new PI(D) controllers in a more Modelica like fashion see: https://github.com/OpenIPSL/OpenIPSL/pull/347/commits/ecd0f280a9fe6eb574e038158d5ad68b524bd731 
Doing so let me wonder why you are using `KDR` in some models but `K_DR` in others same for the `KIR` and `K_IR`. That seems a bit messy. Could this be unified?

2024-11-10 18:36 UTC, GiuseppeLaera commented on OpenIPSL/Electrical/Controls/PSSE/TG/HYGOV.mo
>  </html>",revisions="<html>
You can disregard the changes to HYGOV introduced by my previous commit

2024-11-10 18:37 UTC, GiuseppeLaera commented on OpenIPSL/Electrical/Controls/PSSE/TG/BaseClasses/WEHGOV.mo
> +
Just made a new commit to fix it

2024-11-10 18:37 UTC, GiuseppeLaera commented on OpenIPSL/Electrical/Controls/PSSE/UEL/package.mo
> +package UEL
Just made a new commit to fix it

2024-11-10 18:45 UTC, GiuseppeLaera commented
@dietmarw the confusion about the PI(D) parameters naming comes from the different conventions used in PSSE manuals ("ModelLibrary.pdf" and "PAGV2.pdf"). So the unification is better. Thanks!

2024-11-10 21:37 UTC, dietmarw commented
Ok but still you need to unify them currently both are used one type in AC7B and the other in AC8B. Can this be cleaned up?

2024-11-12 21:22 UTC, dietmarw approved these changes
Looks fine now for me. 
@marcelofcastro  any objections to merge it?

2024-11-14 01:21 UTC, marcelofcastro approved these changes
No objections, @dietmarw and @GiuseppeLaera.

2024-11-14 18:07 UTC, merged